# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Usage' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

pod 'AWIrmFramework', :git => 'https://github.com/adisagar/AwIRMFramework.git' , :tag => '0.0.12'

end
