# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Usage' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  #source 'ssh://git@stash.air-watch.com:7999/~aprasad/msirmpodspec.git'
source 'ssh://git@stash.air-watch.com:7999/icpd/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

pod 'AWIrmFramework', :git => 'https://github.com/adisagar/AwIRMFramework.git' , :tag => ‘0.0.43’
pod 'CompoundFileReader','2.0.0'

#pod 'AWIrmFramework', :git => 'ssh://git@stash.air-watch.com:7999/~aprasad/awirmframework.git' , :tag => ‘0.0.43'

end
